<?php


/**
 * Base class that represents a row from the 'uc_users' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 05/02/14 10:56:10
 *
 * @package    propel.generator...om
 */
abstract class BaseUcUsers extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'UcUsersPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        UcUsersPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinite loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the id field.
     * @var        int
     */
    protected $id;

    /**
     * The value for the user_name field.
     * @var        string
     */
    protected $user_name;

    /**
     * The value for the display_name field.
     * @var        string
     */
    protected $display_name;

    /**
     * The value for the password field.
     * @var        string
     */
    protected $password;

    /**
     * The value for the email field.
     * @var        string
     */
    protected $email;

    /**
     * The value for the activation_token field.
     * @var        string
     */
    protected $activation_token;

    /**
     * The value for the last_activation_request field.
     * @var        int
     */
    protected $last_activation_request;

    /**
     * The value for the lost_password_request field.
     * @var        boolean
     */
    protected $lost_password_request;

    /**
     * The value for the active field.
     * @var        boolean
     */
    protected $active;

    /**
     * The value for the title field.
     * @var        string
     */
    protected $title;

    /**
     * The value for the sign_up_stamp field.
     * @var        int
     */
    protected $sign_up_stamp;

    /**
     * The value for the last_sign_in_stamp field.
     * @var        int
     */
    protected $last_sign_in_stamp;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * Flag to prevent endless clearAllReferences($deep=true) loop, if this object is referenced
     * @var        boolean
     */
    protected $alreadyInClearAllReferencesDeep = false;

    /**
     * Get the [id] column value.
     *
     * @return int
     */
    public function getId()
    {

        return $this->id;
    }

    /**
     * Get the [user_name] column value.
     *
     * @return string
     */
    public function getUserName()
    {

        return $this->user_name;
    }

    /**
     * Get the [display_name] column value.
     *
     * @return string
     */
    public function getDisplayName()
    {

        return $this->display_name;
    }

    /**
     * Get the [password] column value.
     *
     * @return string
     */
    public function getPassword()
    {

        return $this->password;
    }

    /**
     * Get the [email] column value.
     *
     * @return string
     */
    public function getEmail()
    {

        return $this->email;
    }

    /**
     * Get the [activation_token] column value.
     *
     * @return string
     */
    public function getActivationToken()
    {

        return $this->activation_token;
    }

    /**
     * Get the [last_activation_request] column value.
     *
     * @return int
     */
    public function getLastActivationRequest()
    {

        return $this->last_activation_request;
    }

    /**
     * Get the [lost_password_request] column value.
     *
     * @return boolean
     */
    public function getLostPasswordRequest()
    {

        return $this->lost_password_request;
    }

    /**
     * Get the [active] column value.
     *
     * @return boolean
     */
    public function getActive()
    {

        return $this->active;
    }

    /**
     * Get the [title] column value.
     *
     * @return string
     */
    public function getTitle()
    {

        return $this->title;
    }

    /**
     * Get the [sign_up_stamp] column value.
     *
     * @return int
     */
    public function getSignUpStamp()
    {

        return $this->sign_up_stamp;
    }

    /**
     * Get the [last_sign_in_stamp] column value.
     *
     * @return int
     */
    public function getLastSignInStamp()
    {

        return $this->last_sign_in_stamp;
    }

    /**
     * Set the value of [id] column.
     *
     * @param  int $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setId($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->id !== $v) {
            $this->id = $v;
            $this->modifiedColumns[] = UcUsersPeer::ID;
        }


        return $this;
    } // setId()

    /**
     * Set the value of [user_name] column.
     *
     * @param  string $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setUserName($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->user_name !== $v) {
            $this->user_name = $v;
            $this->modifiedColumns[] = UcUsersPeer::USER_NAME;
        }


        return $this;
    } // setUserName()

    /**
     * Set the value of [display_name] column.
     *
     * @param  string $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setDisplayName($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->display_name !== $v) {
            $this->display_name = $v;
            $this->modifiedColumns[] = UcUsersPeer::DISPLAY_NAME;
        }


        return $this;
    } // setDisplayName()

    /**
     * Set the value of [password] column.
     *
     * @param  string $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setPassword($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->password !== $v) {
            $this->password = $v;
            $this->modifiedColumns[] = UcUsersPeer::PASSWORD;
        }


        return $this;
    } // setPassword()

    /**
     * Set the value of [email] column.
     *
     * @param  string $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setEmail($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->email !== $v) {
            $this->email = $v;
            $this->modifiedColumns[] = UcUsersPeer::EMAIL;
        }


        return $this;
    } // setEmail()

    /**
     * Set the value of [activation_token] column.
     *
     * @param  string $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setActivationToken($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->activation_token !== $v) {
            $this->activation_token = $v;
            $this->modifiedColumns[] = UcUsersPeer::ACTIVATION_TOKEN;
        }


        return $this;
    } // setActivationToken()

    /**
     * Set the value of [last_activation_request] column.
     *
     * @param  int $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setLastActivationRequest($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->last_activation_request !== $v) {
            $this->last_activation_request = $v;
            $this->modifiedColumns[] = UcUsersPeer::LAST_ACTIVATION_REQUEST;
        }


        return $this;
    } // setLastActivationRequest()

    /**
     * Sets the value of the [lost_password_request] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setLostPasswordRequest($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->lost_password_request !== $v) {
            $this->lost_password_request = $v;
            $this->modifiedColumns[] = UcUsersPeer::LOST_PASSWORD_REQUEST;
        }


        return $this;
    } // setLostPasswordRequest()

    /**
     * Sets the value of the [active] column.
     * Non-boolean arguments are converted using the following rules:
     *   * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *   * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     * Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     *
     * @param boolean|integer|string $v The new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setActive($v)
    {
        if ($v !== null) {
            if (is_string($v)) {
                $v = in_array(strtolower($v), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
            } else {
                $v = (boolean) $v;
            }
        }

        if ($this->active !== $v) {
            $this->active = $v;
            $this->modifiedColumns[] = UcUsersPeer::ACTIVE;
        }


        return $this;
    } // setActive()

    /**
     * Set the value of [title] column.
     *
     * @param  string $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setTitle($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (string) $v;
        }

        if ($this->title !== $v) {
            $this->title = $v;
            $this->modifiedColumns[] = UcUsersPeer::TITLE;
        }


        return $this;
    } // setTitle()

    /**
     * Set the value of [sign_up_stamp] column.
     *
     * @param  int $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setSignUpStamp($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->sign_up_stamp !== $v) {
            $this->sign_up_stamp = $v;
            $this->modifiedColumns[] = UcUsersPeer::SIGN_UP_STAMP;
        }


        return $this;
    } // setSignUpStamp()

    /**
     * Set the value of [last_sign_in_stamp] column.
     *
     * @param  int $v new value
     * @return UcUsers The current object (for fluent API support)
     */
    public function setLastSignInStamp($v)
    {
        if ($v !== null && is_numeric($v)) {
            $v = (int) $v;
        }

        if ($this->last_sign_in_stamp !== $v) {
            $this->last_sign_in_stamp = $v;
            $this->modifiedColumns[] = UcUsersPeer::LAST_SIGN_IN_STAMP;
        }


        return $this;
    } // setLastSignInStamp()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which resultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
            $this->user_name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
            $this->display_name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
            $this->password = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->email = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
            $this->activation_token = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
            $this->last_activation_request = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
            $this->lost_password_request = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
            $this->active = ($row[$startcol + 8] !== null) ? (boolean) $row[$startcol + 8] : null;
            $this->title = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
            $this->sign_up_stamp = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
            $this->last_sign_in_stamp = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }
            $this->postHydrate($row, $startcol, $rehydrate);

            return $startcol + 12; // 12 = UcUsersPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating UcUsers object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(UcUsersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = UcUsersPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(UcUsersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = UcUsersQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(UcUsersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                UcUsersPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;

        $this->modifiedColumns[] = UcUsersPeer::ID;
        if (null !== $this->id) {
            throw new PropelException('Cannot insert a value for auto-increment primary key (' . UcUsersPeer::ID . ')');
        }

         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(UcUsersPeer::ID)) {
            $modifiedColumns[':p' . $index++]  = '`id`';
        }
        if ($this->isColumnModified(UcUsersPeer::USER_NAME)) {
            $modifiedColumns[':p' . $index++]  = '`user_name`';
        }
        if ($this->isColumnModified(UcUsersPeer::DISPLAY_NAME)) {
            $modifiedColumns[':p' . $index++]  = '`display_name`';
        }
        if ($this->isColumnModified(UcUsersPeer::PASSWORD)) {
            $modifiedColumns[':p' . $index++]  = '`password`';
        }
        if ($this->isColumnModified(UcUsersPeer::EMAIL)) {
            $modifiedColumns[':p' . $index++]  = '`email`';
        }
        if ($this->isColumnModified(UcUsersPeer::ACTIVATION_TOKEN)) {
            $modifiedColumns[':p' . $index++]  = '`activation_token`';
        }
        if ($this->isColumnModified(UcUsersPeer::LAST_ACTIVATION_REQUEST)) {
            $modifiedColumns[':p' . $index++]  = '`last_activation_request`';
        }
        if ($this->isColumnModified(UcUsersPeer::LOST_PASSWORD_REQUEST)) {
            $modifiedColumns[':p' . $index++]  = '`lost_password_request`';
        }
        if ($this->isColumnModified(UcUsersPeer::ACTIVE)) {
            $modifiedColumns[':p' . $index++]  = '`active`';
        }
        if ($this->isColumnModified(UcUsersPeer::TITLE)) {
            $modifiedColumns[':p' . $index++]  = '`title`';
        }
        if ($this->isColumnModified(UcUsersPeer::SIGN_UP_STAMP)) {
            $modifiedColumns[':p' . $index++]  = '`sign_up_stamp`';
        }
        if ($this->isColumnModified(UcUsersPeer::LAST_SIGN_IN_STAMP)) {
            $modifiedColumns[':p' . $index++]  = '`last_sign_in_stamp`';
        }

        $sql = sprintf(
            'INSERT INTO `uc_users` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`id`':
                        $stmt->bindValue($identifier, $this->id, PDO::PARAM_INT);
                        break;
                    case '`user_name`':
                        $stmt->bindValue($identifier, $this->user_name, PDO::PARAM_STR);
                        break;
                    case '`display_name`':
                        $stmt->bindValue($identifier, $this->display_name, PDO::PARAM_STR);
                        break;
                    case '`password`':
                        $stmt->bindValue($identifier, $this->password, PDO::PARAM_STR);
                        break;
                    case '`email`':
                        $stmt->bindValue($identifier, $this->email, PDO::PARAM_STR);
                        break;
                    case '`activation_token`':
                        $stmt->bindValue($identifier, $this->activation_token, PDO::PARAM_STR);
                        break;
                    case '`last_activation_request`':
                        $stmt->bindValue($identifier, $this->last_activation_request, PDO::PARAM_INT);
                        break;
                    case '`lost_password_request`':
                        $stmt->bindValue($identifier, (int) $this->lost_password_request, PDO::PARAM_INT);
                        break;
                    case '`active`':
                        $stmt->bindValue($identifier, (int) $this->active, PDO::PARAM_INT);
                        break;
                    case '`title`':
                        $stmt->bindValue($identifier, $this->title, PDO::PARAM_STR);
                        break;
                    case '`sign_up_stamp`':
                        $stmt->bindValue($identifier, $this->sign_up_stamp, PDO::PARAM_INT);
                        break;
                    case '`last_sign_in_stamp`':
                        $stmt->bindValue($identifier, $this->last_sign_in_stamp, PDO::PARAM_INT);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        try {
            $pk = $con->lastInsertId();
        } catch (Exception $e) {
            throw new PropelException('Unable to get autoincrement id.', $e);
        }
        $this->setId($pk);

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        }

        $this->validationFailures = $res;

        return false;
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggregated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objects otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            if (($retval = UcUsersPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }



            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = UcUsersPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getId();
                break;
            case 1:
                return $this->getUserName();
                break;
            case 2:
                return $this->getDisplayName();
                break;
            case 3:
                return $this->getPassword();
                break;
            case 4:
                return $this->getEmail();
                break;
            case 5:
                return $this->getActivationToken();
                break;
            case 6:
                return $this->getLastActivationRequest();
                break;
            case 7:
                return $this->getLostPasswordRequest();
                break;
            case 8:
                return $this->getActive();
                break;
            case 9:
                return $this->getTitle();
                break;
            case 10:
                return $this->getSignUpStamp();
                break;
            case 11:
                return $this->getLastSignInStamp();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array())
    {
        if (isset($alreadyDumpedObjects['UcUsers'][$this->getPrimaryKey()])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['UcUsers'][$this->getPrimaryKey()] = true;
        $keys = UcUsersPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getId(),
            $keys[1] => $this->getUserName(),
            $keys[2] => $this->getDisplayName(),
            $keys[3] => $this->getPassword(),
            $keys[4] => $this->getEmail(),
            $keys[5] => $this->getActivationToken(),
            $keys[6] => $this->getLastActivationRequest(),
            $keys[7] => $this->getLostPasswordRequest(),
            $keys[8] => $this->getActive(),
            $keys[9] => $this->getTitle(),
            $keys[10] => $this->getSignUpStamp(),
            $keys[11] => $this->getLastSignInStamp(),
        );
        $virtualColumns = $this->virtualColumns;
        foreach ($virtualColumns as $key => $virtualColumn) {
            $result[$key] = $virtualColumn;
        }


        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = UcUsersPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setId($value);
                break;
            case 1:
                $this->setUserName($value);
                break;
            case 2:
                $this->setDisplayName($value);
                break;
            case 3:
                $this->setPassword($value);
                break;
            case 4:
                $this->setEmail($value);
                break;
            case 5:
                $this->setActivationToken($value);
                break;
            case 6:
                $this->setLastActivationRequest($value);
                break;
            case 7:
                $this->setLostPasswordRequest($value);
                break;
            case 8:
                $this->setActive($value);
                break;
            case 9:
                $this->setTitle($value);
                break;
            case 10:
                $this->setSignUpStamp($value);
                break;
            case 11:
                $this->setLastSignInStamp($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = UcUsersPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setUserName($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setDisplayName($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setPassword($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setEmail($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setActivationToken($arr[$keys[5]]);
        if (array_key_exists($keys[6], $arr)) $this->setLastActivationRequest($arr[$keys[6]]);
        if (array_key_exists($keys[7], $arr)) $this->setLostPasswordRequest($arr[$keys[7]]);
        if (array_key_exists($keys[8], $arr)) $this->setActive($arr[$keys[8]]);
        if (array_key_exists($keys[9], $arr)) $this->setTitle($arr[$keys[9]]);
        if (array_key_exists($keys[10], $arr)) $this->setSignUpStamp($arr[$keys[10]]);
        if (array_key_exists($keys[11], $arr)) $this->setLastSignInStamp($arr[$keys[11]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(UcUsersPeer::DATABASE_NAME);

        if ($this->isColumnModified(UcUsersPeer::ID)) $criteria->add(UcUsersPeer::ID, $this->id);
        if ($this->isColumnModified(UcUsersPeer::USER_NAME)) $criteria->add(UcUsersPeer::USER_NAME, $this->user_name);
        if ($this->isColumnModified(UcUsersPeer::DISPLAY_NAME)) $criteria->add(UcUsersPeer::DISPLAY_NAME, $this->display_name);
        if ($this->isColumnModified(UcUsersPeer::PASSWORD)) $criteria->add(UcUsersPeer::PASSWORD, $this->password);
        if ($this->isColumnModified(UcUsersPeer::EMAIL)) $criteria->add(UcUsersPeer::EMAIL, $this->email);
        if ($this->isColumnModified(UcUsersPeer::ACTIVATION_TOKEN)) $criteria->add(UcUsersPeer::ACTIVATION_TOKEN, $this->activation_token);
        if ($this->isColumnModified(UcUsersPeer::LAST_ACTIVATION_REQUEST)) $criteria->add(UcUsersPeer::LAST_ACTIVATION_REQUEST, $this->last_activation_request);
        if ($this->isColumnModified(UcUsersPeer::LOST_PASSWORD_REQUEST)) $criteria->add(UcUsersPeer::LOST_PASSWORD_REQUEST, $this->lost_password_request);
        if ($this->isColumnModified(UcUsersPeer::ACTIVE)) $criteria->add(UcUsersPeer::ACTIVE, $this->active);
        if ($this->isColumnModified(UcUsersPeer::TITLE)) $criteria->add(UcUsersPeer::TITLE, $this->title);
        if ($this->isColumnModified(UcUsersPeer::SIGN_UP_STAMP)) $criteria->add(UcUsersPeer::SIGN_UP_STAMP, $this->sign_up_stamp);
        if ($this->isColumnModified(UcUsersPeer::LAST_SIGN_IN_STAMP)) $criteria->add(UcUsersPeer::LAST_SIGN_IN_STAMP, $this->last_sign_in_stamp);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(UcUsersPeer::DATABASE_NAME);
        $criteria->add(UcUsersPeer::ID, $this->id);

        return $criteria;
    }

    /**
     * Returns the primary key for this object (row).
     * @return int
     */
    public function getPrimaryKey()
    {
        return $this->getId();
    }

    /**
     * Generic method to set the primary key (id column).
     *
     * @param  int $key Primary key.
     * @return void
     */
    public function setPrimaryKey($key)
    {
        $this->setId($key);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return null === $this->getId();
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of UcUsers (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setUserName($this->getUserName());
        $copyObj->setDisplayName($this->getDisplayName());
        $copyObj->setPassword($this->getPassword());
        $copyObj->setEmail($this->getEmail());
        $copyObj->setActivationToken($this->getActivationToken());
        $copyObj->setLastActivationRequest($this->getLastActivationRequest());
        $copyObj->setLostPasswordRequest($this->getLostPasswordRequest());
        $copyObj->setActive($this->getActive());
        $copyObj->setTitle($this->getTitle());
        $copyObj->setSignUpStamp($this->getSignUpStamp());
        $copyObj->setLastSignInStamp($this->getLastSignInStamp());
        if ($makeNew) {
            $copyObj->setNew(true);
            $copyObj->setId(NULL); // this is a auto-increment column, so set to default value
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return UcUsers Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return UcUsersPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new UcUsersPeer();
        }

        return self::$peer;
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->id = null;
        $this->user_name = null;
        $this->display_name = null;
        $this->password = null;
        $this->email = null;
        $this->activation_token = null;
        $this->last_activation_request = null;
        $this->lost_password_request = null;
        $this->active = null;
        $this->title = null;
        $this->sign_up_stamp = null;
        $this->last_sign_in_stamp = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->alreadyInClearAllReferencesDeep = false;
        $this->clearAllReferences();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volume/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep && !$this->alreadyInClearAllReferencesDeep) {
            $this->alreadyInClearAllReferencesDeep = true;

            $this->alreadyInClearAllReferencesDeep = false;
        } // if ($deep)

    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(UcUsersPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

}
