<?php



/**
 * Skeleton subclass for representing a row from the 'uc_configuration' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 05/02/14 10:53:08
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator..
 */
class UcConfiguration extends BaseUcConfiguration
{
}
