<?php
/**
 * Skeleton subclass for performing query and update operations on the 'uc_users' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.7.0 on:
 *
 * 05/02/14 10:56:10
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator..
 */
class UcUsersQuery extends BaseUcUsersQuery
{
	public function __construct(){
		parent::__construct();
	}
}
?>